feat: Build wasp-cli for checking all arch

diff --git a/.github/workflows/build-test.yml b/.github/workflows/build-test.yml
--- a/.github/workflows/build-test.yml
+++ b/.github/workflows/build-test.yml
@@ -108,3 +108,57 @@ jobs:
           version: v1.54.2
           args: --timeout 15m0s
           skip-pkg-cache: true
+
+  build-wasp-cli: 
+    runs-on: ubuntu-latest
+    steps:
+      - name: Set up Go 1.x
+        uses: actions/setup-go@v4
+        with:
+          go-version: "1.21"
+        id: go
+
+      - name: Check out code into the Go module directory
+        uses: actions/checkout@v4
+
+      - name: Get dependencies
+        run: |
+          make wasm
+          go get -v -t -d ./...
+
+      - name: macos arm64
+        run: |
+          GOOS=darwin GOARCH=arm64 make build-cli 
+          if [ -f wasp-cli ]; then
+            rm wasp-cli
+          else
+            echo "error: can't compile wasp-cli"
+            exit 1
+          fi
+      - name: macos amd64
+        run: |
+          GOOS=darwin GOARCH=amd64 make build-cli 
+          if [ -f wasp-cli ]; then
+            rm wasp-cli
+          else
+            echo "error: can't compile wasp-cli"
+            exit 1
+          fi
+      - name: linux arm64
+        run: |
+          GOOS=linux GOARCH=arm64 make build-cli 
+          if [ -f wasp-cli ]; then
+            rm wasp-cli
+          else
+            echo "error: can't compile wasp-cli"
+            exit 1
+          fi
+      - name: linux amd64
+        run: |
+          GOOS=linux GOARCH=amd64 make build-cli 
+          if [ -f wasp-cli ]; then
+            rm wasp-cli
+          else
+            echo "error: can't compile wasp-cli"
+            exit 1
+          fi
